mark_as_advanced(WSLAY_INCLUDE_DIRS WSLAY_STATIC_LIB)

find_path(WSLAY_INCLUDE_DIRS NAMES wslay.h PATH_SUFFIXES wslay)
find_library(WSLAY_STATIC_LIB NAMES libwslay.a)

if(WSLAY_INCLUDE_DIRS AND WSLAY_STATIC_LIB)
  set(WSLAY_FOUND ON)
  set(WSLAY_LIBRARIES ${WSLAY_STATIC_LIB})
  message("WSLAY Found ${WSLAY_LIBRARIES} ${WSLAY_INCLUDE_DIRS}")
else()
  message(FATAL_ERROR "WSLAY Not Found" )
  set(WSLAY-NOTFOUND ON)
endif()
